// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// 🔥 Firebase 프로젝트 설정 방법:
/// 1. Firebase Console (https://console.firebase.google.com) 접속
/// 2. 프로젝트 생성 또는 기존 프로젝트 선택
/// 3. 프로젝트 설정 > 일반 > 앱 추가 > 웹 앱
/// 4. 앱 등록 후 표시되는 설정값을 아래에 입력
/// 5. 이 파일을 firebase_options.dart로 복사하여 실제 값 입력
///
/// 📋 필요한 Firebase 서비스:
/// - Authentication (이메일/비밀번호, Google)
/// - Cloud Storage (프로필 사진 업로드)
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration
  static const FirebaseOptions web = FirebaseOptions(
    // 🔑 API Key - Firebase Console에서 복사
    apiKey: 'AIzaSy...YOUR_API_KEY',

    // 📱 App ID - Firebase Console에서 복사
    appId: '1:123456789:web:abc...YOUR_APP_ID',

    // 📨 Messaging Sender ID - Firebase Console에서 복사
    messagingSenderId: '123456789',

    // 🏷️ Project ID - Firebase Console에서 복사
    projectId: 'your-project-id',

    // 🌐 Auth Domain - 보통 projectId.firebaseapp.com 형식
    authDomain: 'your-project-id.firebaseapp.com',

    // 💾 Storage Bucket - 보통 projectId.appspot.com 형식
    storageBucket: 'your-project-id.appspot.com',

    // 📊 Measurement ID (선택사항, Google Analytics 사용 시)
    measurementId: 'G-XXXXXXXXXX',
  );
}
